# Generated by Django 4.2.23 on 2025-08-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("video", models.FileField(upload_to="videos/")),
                (
                    "mind_file",
                    models.FileField(blank=True, null=True, upload_to="targets/"),
                ),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
