# Generated by Django 4.2.23 on 2025-08-22 04:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arexp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="upload",
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.AddField(
            model_name="upload",
            name="target_name",
            field=models.CharField(
                db_index=True,
                default="legacy",
                help_text="8th Wall Image Target name",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="upload",
            name="video",
            field=models.FileField(
                upload_to="videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm"]
                    )
                ],
            ),
        ),
    ]
