# Generated by Django 4.2.23 on 2025-08-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arexp", "0002_alter_upload_options_upload_target_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ARExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Name of the AR experience", max_length=200
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, help_text="URL-friendly identifier", unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the AR experience"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Image to be used as AR marker (JPG, PNG recommended)",
                        upload_to="markers/",
                    ),
                ),
                (
                    "model_file",
                    models.FileField(
                        blank=True,
                        help_text="3D model file (GLB, GLTF, OBJ)",
                        null=True,
                        upload_to="models/",
                    ),
                ),
                (
                    "content_text",
                    models.TextField(
                        blank=True, help_text="Text content to display in AR"
                    ),
                ),
                (
                    "content_url",
                    models.URLField(blank=True, help_text="URL to additional content"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this experience is active"
                    ),
                ),
                (
                    "marker_generated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether marker files have been generated",
                    ),
                ),
                (
                    "marker_size",
                    models.FloatField(
                        default=1.0, help_text="Size of the marker in AR space"
                    ),
                ),
            ],
            options={
                "verbose_name": "AR Experience",
                "verbose_name_plural": "AR Experiences",
                "ordering": ["-created_at"],
            },
        ),
    ]
