# Generated by Django 4.2.23 on 2025-08-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arexp", "0003_arexperience"),
    ]

    operations = [
        migrations.AddField(
            model_name="arexperience",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
