# Generated by Django 4.2.23 on 2025-08-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arexp", "0004_arexperience_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="arexperience",
            name="qr_code",
            field=models.FileField(blank=True, null=True, upload_to="qrcodes/"),
        ),
    ]
