# Generated by Django 4.2.23 on 2025-08-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arexp", "0005_arexperience_qr_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arexperience",
            name="content_text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="arexperience",
            name="content_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="arexperience",
            name="image",
            field=models.ImageField(upload_to="markers/"),
        ),
        migrations.AlterField(
            model_name="arexperience",
            name="marker_size",
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name="arexperience",
            name="model_file",
            field=models.FileField(blank=True, null=True, upload_to="models/"),
        ),
    ]
