# Generated by Django 4.2.23 on 2025-08-23 05:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arexp", "0006_alter_arexperience_content_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arexperience",
            name="content_text",
            field=models.TextField(
                blank=True, help_text="Optional text content to display"
            ),
        ),
        migrations.AlterField(
            model_name="arexperience",
            name="image",
            field=models.ImageField(
                help_text="Image to be used as AR marker (JPG, PNG recommended)",
                upload_to="markers/",
            ),
        ),
        migrations.AlterField(
            model_name="arexperience",
            name="model_file",
            field=models.FileField(
                blank=True,
                help_text="Optional 3D model file (GLB, GLTF, USDZ)",
                null=True,
                upload_to="models/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["glb", "gltf", "usdz"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="arexperience",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Optional video to display in AR experience",
                null=True,
                upload_to="videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm"]
                    )
                ],
            ),
        ),
    ]
