# Generated by Django 4.2.23 on 2025-08-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arexp", "0007_alter_arexperience_content_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arexperience",
            name="content_url",
            field=models.URLField(blank=True, help_text="URL to additional content"),
        ),
        migrations.AlterField(
            model_name="arexperience",
            name="marker_size",
            field=models.FloatField(
                default=1.0, help_text="Size of the marker in AR space"
            ),
        ),
    ]
