# Generated by Django 4.2.23 on 2025-08-25 09:16

import arexp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arexp", "0008_alter_arexperience_content_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arexperience",
            name="image",
            field=models.ImageField(
                help_text="Image to be used as AR marker",
                upload_to=arexp.models.ar_marker_image_path,
            ),
        ),
        migrations.AlterField(
            model_name="arexperience",
            name="model_file",
            field=models.FileField(
                blank=True,
                help_text="Optional 3D model file",
                null=True,
                upload_to=arexp.models.ar_model_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["glb", "gltf", "usdz"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="arexperience",
            name="qr_code",
            field=models.FileField(
                blank=True, null=True, upload_to=arexp.models.ar_qr_path
            ),
        ),
        migrations.AlterField(
            model_name="arexperience",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="arexperience",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Optional video to display in AR experience",
                null=True,
                upload_to=arexp.models.ar_video_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="upload",
            name="image",
            field=models.ImageField(upload_to=arexp.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name="upload",
            name="mind_file",
            field=models.FileField(
                blank=True, null=True, upload_to=arexp.models.upload_mind_file_path
            ),
        ),
        migrations.AlterField(
            model_name="upload",
            name="video",
            field=models.FileField(
                upload_to=arexp.models.upload_video_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm"]
                    )
                ],
            ),
        ),
    ]
