# Generated by Django 4.2.23 on 2025-09-01 08:55

import arexp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arexp", "0009_alter_arexperience_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="arexperience",
            name="nft_fset3_file",
            field=models.FileField(
                blank=True,
                editable=False,
                help_text="NFT marker .fset3 file (automatically generated)",
                null=True,
                upload_to=arexp.models.ar_nft_path,
            ),
        ),
        migrations.AddField(
            model_name="arexperience",
            name="nft_fset_file",
            field=models.FileField(
                blank=True,
                editable=False,
                help_text="NFT marker .fset file (automatically generated)",
                null=True,
                upload_to=arexp.models.ar_nft_path,
            ),
        ),
        migrations.AddField(
            model_name="arexperience",
            name="nft_iset_file",
            field=models.FileField(
                blank=True,
                editable=False,
                help_text="NFT marker .iset file (automatically generated)",
                null=True,
                upload_to=arexp.models.ar_nft_path,
            ),
        ),
    ]
