# Generated by Django 4.2.23 on 2025-09-13 08:49

import arexp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arexp", "0010_arexperience_nft_fset3_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arexperience",
            name="nft_fset3_file",
            field=models.FileField(
                blank=True,
                editable=False,
                null=True,
                upload_to=arexp.models.ar_nft_path,
            ),
        ),
        migrations.AlterField(
            model_name="arexperience",
            name="nft_fset_file",
            field=models.FileField(
                blank=True,
                editable=False,
                null=True,
                upload_to=arexp.models.ar_nft_path,
            ),
        ),
        migrations.AlterField(
            model_name="arexperience",
            name="nft_iset_file",
            field=models.FileField(
                blank=True,
                editable=False,
                null=True,
                upload_to=arexp.models.ar_nft_path,
            ),
        ),
    ]
