# Generated by Django 4.2.23 on 2025-09-17 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("arexp", "0011_alter_arexperience_nft_fset3_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="arexperience",
            name="user",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Optional user who created this AR experience",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="arexperience",
            name="view_count",
            field=models.IntegerField(
                default=0, help_text="Number of times this experience has been viewed"
            ),
        ),
        migrations.AddField(
            model_name="arexperience",
            name="visibility",
            field=models.CharField(
                default="public",
                help_text="Visibility setting for the experience",
                max_length=20,
            ),
        ),
    ]
